import mysql.connector
conn = mysql.connector.connect(user='root',password='root',database='test',host='127.0.0.1',charset='utf8')
cursor = conn.cursor()
cursor.execute('create table user (id varchar(20) primary key,name varchar(20))')
cursor.execute('insert into user values (%s,%s)',['1','Twittytop'])
print(cursor.rowcount)
conn.commit()
cursor.close()

cursor = conn.cursor()
cursor.execute('select name from user where id = %s',('1',))
values = cursor.fetchall()
print(values)
cursor.close()
conn.close()